### ISSUE TITLE
Add support for uint16 and uint32

### ISSUE THREAD

**Issue by karalabe** [karalabe/ssz#12]
Adding the support is analogous to https://github.com/karalabe/ssz/pull/10, just look at uint64 for the little endian handling instead.

Adding the tests can be done via adding the uint16/32 types from here: https://github.com/ethereum/consensus-specs/blob/e9be4e2e3aeb8d0fbe3bff800328445e21a1fdf3/tests/generators/ssz_generic/ssz_container.py#L14, specifically SmallTestStruct, FixedTestStruct, VarTestStruct and ComplexTestStruct as done https://github.com/karalabe/ssz/pull/11/files#diff-2eb949c59ea6f7b5ead391aeccb29b795000d268c46d983c6142cef2651d72c1 and called in the tests.

**Comment by raxhvl** [comment]
I have no idea what this is. But I'm in. Will keep you posted.

**Comment by Lavishq** [comment]
saw it on twitter (x) and didnt know what that is but started working on it-
as the resources was provided it was ez :)`

https://github.com/karalabe/ssz/pull/15

**Comment by karalabe** [comment]
Done via https://github.com/karalabe/ssz/pull/15
