### ISSUE TITLE
bug(serialization): round-trip is not the same

### ISSUE THREAD

**Issue by itsdevbear** [karalabe/ssz#18]
Linking from BeaconKit repo: https://github.com/berachain/beacon-kit/pull/1834

**Comment by itsdevbear** [comment]
cc: @sbudella-gco

cc

**Comment by karalabe** [comment]
Sorry, was on holiday last week. Will try to work my way through these soon.

**Comment by itsdevbear** [comment]
all good, hope it was fun!
